### ISSUE TITLE
Docnet Cannot open valid issues with certain characters (ſ)

### ISSUE THREAD

**Issue by majora2007** [GowenGit/docnet#80]
**Describe the bug**
Docnet is unable to open some valid files, with non-english characters, like `ſ``.

```
Docnet.Core.Exceptions.DocnetLoadDocumentException: unable to open the document: ErrorCode=2, ReasonPhrase=file not found or could not be opened
   at Docnet.Core.Bindings.DocumentWrapper..ctor(String filePath, String password)
   at Docnet.Core.Readers.DocReader..ctor(String filePath, String password, PageDimensions dimensions)
   at Docnet.Core.DocLib.GetDocReader(String filePath, String password, PageDimensions dimensionOptions)
   at Docnet.Core.DocLib.GetDocReader(String filePath, PageDimensions dimensionOptions)
   at API.Services.BookService.GetNumberOfPages(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 485
   ```

**To Reproduce**
1. [Download](https://www.gutenberg.org/files/42911/Bizet-Variations_Chromatiques_de_concert/Bizet-Variations_Chromatiques_de_concert_Theme_A4.pdf) a pdf and rename it as "test_ſ`.pdf" 
2. Attempt to open the PDF
```
using var docReader = DocLib.Instance.GetDocReader(filePath, new PageDimensions(1080, 1920));
```
3. See exception raised
Expected: Since the file is valid, the docReader should open without error. 

**Expected behavior**
If a file is valid and exists, docnet should be able to open it. If you remove the `ſ`` character it will open fine. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET 6

**Additional context**
[Issue reported originally here](https://github.com/Kareadita/Kavita/issues/1435)

**Comment by majora2007** [comment]
Closing this issue, updating to the latest alpha fixes this.
